version: "3"
services:
  plugin.video.mlbserver:
    image: tonywagner/plugin.video.mlbserver
    container_name: plugin.video.mlbserver
    environment:
      - TZ=America/New_York
    ports:
      - 5714:5714
    volumes:
      - ./data:/plugin.video.mlb/data
    restart: unless-stopped